<!doctype html><html lang="it"><head><meta charset="UTF-8"><title>Gestione Esami</title><link rel="stylesheet" href="{$request.contextPath}/css/style.css"><link rel="stylesheet" href="{$request.contextPath}/css/tabella.css"><link rel="stylesheet" href="{$request.contextPath}/css/prenotazioni.css"><link rel="stylesheet" href="{$request.contextPath}/css/calendario.css"></head><body>
<header><h1>DriveMeSafely - Area Personale</h1><nav><a href="{$request.contextPath}/home/segreteria">Home</a> <a href="{$request.contextPath}/home/logout">Logout</a></nav></header>
<main class="lezioni-container"><h2>🖥️ Gestione Esami</h2>
{if $errore}<div class="alert alert-error">⚠️ {$errore|escape}</div>{/if}
{if $successo == 'annullamento'}<div class="alert alert-success">✔️ Prenotazione annullata con successo!</div>{elseif $successo == 'esito_registrato'}<div class="alert alert-success">✔️ Esito registrato con successo!</div>{elseif $successo == 'esito_modificato'}<div class="alert alert-success">✔️ Esito modificato con successo!</div>{elseif $successo == 'esito_annullato'}<div class="alert alert-success">✔️ Esito annullato con successo!</div>{elseif $successo}<div class="alert alert-success">✔️ Prenotazione effettuata con successo!</div>{/if}
<div class="form-box"><h3>📅 Prenotazione sessione</h3><form method="get"><label>Sessione
<select name="idEsame" onchange="this.form.submit()"><option value="">-- Scegli --</option>{foreach $esamiDisponibili as $esame}<option value="{$esame->getIdEsame()}" {if $idEsameSelezionato == $esame->getIdEsame()}selected{/if}>[{$esame->getTipologia()->getDescrizione()}] {$esame->getDataOraFormattata()}</option>{/foreach}</select></label></form>
{if $idEsameSelezionato}<form method="post"><input type="hidden" name="idEsame" value="{$idEsameSelezionato}"><fieldset><legend>Allievi idonei (selezionabili più contemporaneamente)</legend>{foreach $iscrittiIdonei as $iscritto}<label class="checkbox-item"><input type="checkbox" name="idIscritti[]" value="{$iscritto->getId()}"> {$iscritto->getCognome()} {$iscritto->getNome()} - Patente {$iscritto->getTipoPatente()->getTipo()}</label>{foreachelse}<p>Nessun allievo idoneo</p>{/foreach}</fieldset><button type="submit">✓ Conferma iscrizioni</button></form>{/if}</div>
<section class="calendar-card">
<div class="calendar-header"><h2>📅 Calendario esami</h2><p>Visualizza tutte le sessioni d'esame in programma.</p></div>
<div id="calendar"></div>
<div class="calendar-legend"><span>🔵 Esami pratici</span><span>🟣 Esami teoria</span></div>
</section>
<h3>📋 Storico prenotazioni</h3><table><thead><tr><th>Allievo</th><th>Tipologia</th><th>Data</th><th>Stato</th><th>Esito</th><th>Azioni</th></tr></thead><tbody>{foreach $storicoPrenotazioni as $p}{assign var="idPrenotazioneStorico" value=$p->getIdPrenotazioneEsame()}{if isset($effettuazioniPerPrenotazione[$idPrenotazioneStorico])}{assign var="effettuazione" value=$effettuazioniPerPrenotazione[$idPrenotazioneStorico]}{else}{assign var="effettuazione" value=null}{/if}<tr><td>{$p->getAllievo()->getCognome()} {$p->getAllievo()->getNome()}</td><td>{$p->getEsame()->getTipologia()->getDescrizione()}</td><td>{$p->getEsame()->getDataOraFormattata()}</td><td><span class="badge stato-{$p->getStato()->value|lower}">{$p->getStato()->getDescrizione()|escape}</span></td><td>{if $effettuazione}<span class="stato-badge {if $effettuazione->isSuperato()}stato-superato{else}stato-non-superato{/if}">{if $effettuazione->isSuperato()}✓ Superato{else}✕ Non superato{/if}</span>{else}<span class="muted">—</span>{/if}</td><td>
{if !$effettuazione && $p->getStato()->isAttiva()}<form method="post" action="{$request.contextPath}/home/segreteria/gestione_esami/annulla" class="inline-form"><input type="hidden" name="idPrenotazione" value="{$p->getIdPrenotazioneEsame()}"><button type="submit" class="btn-annulla" onclick="return confirm('Sei sicuro di voler annullare questa prenotazione?');">Annulla prenotazione</button></form>
{if in_array($p->getIdPrenotazioneEsame(), $prenotazioniSvolte)}<form method="post" action="{$request.contextPath}/home/segreteria/gestione_esami/registra_esito" class="inline-form"><input type="hidden" name="idPrenotazione" value="{$p->getIdPrenotazioneEsame()}"><input type="hidden" name="tentativi" value="1"><label><input type="checkbox" name="superato" value="1"> Superato</label><button type="submit">Registra esito</button></form>{/if}
{elseif $effettuazione}<form method="post" action="{$request.contextPath}/home/segreteria/gestione_esami/modifica_esito" class="inline-form"><input type="hidden" name="idEffettuazione" value="{$effettuazione->getId()}"><input type="hidden" name="tentativi" value="{$effettuazione->getTentativi()}"><label><input type="checkbox" name="superato" value="1" {if $effettuazione->isSuperato()}checked{/if}> Superato</label><button type="submit">Modifica</button></form>
{else}<span class="muted">—</span>{/if}
</td></tr>{foreachelse}<tr><td colspan="6">Nessuna prenotazione.</td></tr>{/foreach}</tbody></table>
</main>
<script>window.eventiEsami = {$eventiCalendario nofilter};</script>
<script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.19/index.global.min.js"></script>
<script src="{$request.contextPath}/js/esame_calendar.js"></script>
</body></html>
