<!doctype html><html lang="it"><head><meta charset="UTF-8"><title>Gestione Esami</title><link rel="stylesheet" href="{$request.contextPath}/css/style.css"><link rel="stylesheet" href="{$request.contextPath}/css/tabella.css"><link rel="stylesheet" href="{$request.contextPath}/css/prenotazioni.css"></head><body>
<header><h1>DriveMeSafely - Area Personale</h1><nav><a href="{$homeUrl}">Home</a> <a href="{$request.contextPath}/home/logout">Logout</a></nav></header>
<main class="lezioni-container"><h2>🖥️ Gestione Esami</h2>
{if $errore}<div class="alert alert-error">⚠️ {$errore|escape}</div>{/if}{if $successo}<div class="alert alert-success">✔️ Prenotazione effettuata con successo!</div>{/if}
<div class="form-box"><h3>📅 Prenotazione sessione</h3><form method="get"><label>Sessione
<select name="idEsame" onchange="this.form.submit()"><option value="">-- Scegli --</option>{foreach $esamiDisponibili as $esame}<option value="{$esame->getIdEsame()}" {if $idEsameSelezionato == $esame->getIdEsame()}selected{/if}>[{$esame->getTipologia()->getDescrizione()}] {$esame->getDataOraFormattata()}</option>{/foreach}</select></label></form>
{if $idEsameSelezionato}<form method="post"><input type="hidden" name="idEsame" value="{$idEsameSelezionato}"><label>Allievi idonei<select name="idIscritti[]" multiple size="6" required>{foreach $iscrittiIdonei as $iscritto}<option value="{$iscritto->getId()}">{$iscritto->getCognome()} {$iscritto->getNome()}</option>{foreachelse}<option disabled>Nessun allievo idoneo</option>{/foreach}</select></label><button type="submit">✓ Conferma iscrizioni</button></form>{/if}</div>
<h3>📋 Storico prenotazioni</h3><table><thead><tr><th>Allievo</th><th>Tipologia</th><th>Data</th><th>Stato</th></tr></thead><tbody>{foreach $storicoPrenotazioni as $p}<tr><td>{$p->getAllievo()->getCognome()} {$p->getAllievo()->getNome()}</td><td>{$p->getEsame()->getTipologia()->getDescrizione()}</td><td>{$p->getEsame()->getDataOraFormattata()}</td><td>{$p->getStato()}</td></tr>{foreachelse}<tr><td colspan="4">Nessuna prenotazione.</td></tr>{/foreach}</tbody></table>
</main></body></html>
